name: Deploy Dev
on:
  push:
    branches:
      - develop
      
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Deploy Lambda functions
      run: sls deploy -s dev
    - name: Update .env
      run: aws lambda update-function-configuration --function-name serverless-node-ms-boilerplate \ --environment "$(echo "{\"Variables\":$(doppler secrets download --no-file)}")"
